
services:
  
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_DB: db_associates
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vini123
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped


  backend:
    build: ./Backend
    ports:
      - "8000:80"
    volumes:
      - ./Backend:/code
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:vini123@database:5432/db_associates
    depends_on:
      - database

  frontend:
    build: ./Frontend
    ports:
      - "8080:8080"
    volumes:
      - ./Frontend:/app
    environment:
      - NODE_ENV=development
  
volumes:
  postgres_data:
  


