version: "3.9"

services:
  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/code
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - frontend

  frontend:
    build: ./Frontend
    ports:
      - "8080:8080"
    volumes:
      - ./Frontend:/app
    environment:
      - NODE_ENV=development
